-- AlterTable
ALTER TABLE "Resume" ADD COLUMN IF NOT EXISTS "name" TEXT,
ADD COLUMN IF NOT EXISTS "atsScore" INTEGER,
ADD COLUMN IF NOT EXISTS "atsGrade" TEXT,
ADD COLUMN IF NOT EXISTS "improvementActions" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;



